#!/bin/bash
#set -x

REMOTE_HOSTS="r-learn-c-east1b-vm-1 r-learn-c-east1b-vm-2"
SERIES_NICKNAME="NWO"
SERIES_INDEXES="1 2 3 4"
# SERIES_xS_SPEC=~/Documents/dev/projects/${SERIES_NICKNAME}/ginDQNParameters.py."${SERIES_NICKNAME}"
REMOTE_ID="edward_schwarz" 
PARAMS_SOURCE_MODEL_NICKNAME=HOT.3.5
PARAMS_SOURCE_VM=r-learn-b-cent1a-vm-1
PARAMS_FILE=ginDQNParameters.py."${PARAMS_SOURCE_MODEL_NICKNAME}"
PARAMS_TARGET_PATH="~/dev/projects/training_ground/${PARAMS_SOURCE_MODEL_NICKNAME}"
PARAMS_RP="${REMOTE_ID}"@"${PARAMS_SOURCE_VM}"
SERIES_PARAMS_SPEC=${PARAMS_RP}:"${PARAMS_TARGET_PATH}"/"${PARAMS_FILE}"

CURRENT_SCRIPT_NAME="`basename ${0}`"
CURRENT_SCRIPT_SOURCE_DIR="`dirname ${0}`"
CURRENT_SCRIPT_ORIGINAL_EXECUTION_DIR=`pwd`

echo "*********** ${CURRENT_SCRIPT_NAME}: execution at `date` ***********"
echo REMOTE_HOSTS="${REMOTE_HOSTS}"
echo SERIES_NICKNAME="${SERIES_NICKNAME}"
echo SERIES_INDEXES="${SERIES_INDEXES}"
echo SERIES_PARAMS_SPEC="${SERIES_PARAMS_SPEC}"

echo ${CURRENT_SCRIPT_SOURCE_DIR}/series_remote_bootstrap "${REMOTE_HOSTS}"  "${SERIES_NICKNAME}"  "${SERIES_INDEXES}" "${SERIES_PARAMS_SPEC}"
${CURRENT_SCRIPT_SOURCE_DIR}/series_remote_bootstrap.sh "${REMOTE_HOSTS}"  "${SERIES_NICKNAME}" "${SERIES_INDEXES}" "${SERIES_PARAMS_SPEC}"


